-- Latest security snapshot fact table for dashboard screening.
{{ config(materialized = 'table') }}

SELECT
    MD5(ticker) AS security_key,
    MD5(COALESCE(sector, 'Unknown')) AS sector_key,
    TO_NUMBER(TO_CHAR(latest_trade_date, 'YYYYMMDD')) AS date_key,
    latest_trade_date,

    latest_volume,
    latest_open,
    latest_close,
    latest_prev_close,
    latest_high,
    latest_low,
    latest_sma20,
    latest_sma50,
    latest_sma200,
    latest_rsi,
    latest_rel_vol,
    latest_52week_high,
    latest_52week_low,
    price_change_1d,
    return_1d,
    return_1w,
    return_1m,
    return_3m,
    return_ytd,
    pct_distance_from_52week_high,
    pct_distance_from_52week_low,
    total_trading_days,
    sector_return_1m,
    performance_percentile,
    outperformance_vs_sector,
    volatility_20d,
    avg_volume_20d,
    has_golden_cross_active,
    over_sma20,
    over_sma50,
    over_sma200,
    days_since_last_golden_cross,
    days_over_sma50,
    days_under_sma50
FROM {{ ref('prep_security_current_snapshot') }}
